### ISSUE TITLE
There are some broken links in lab1 [JP].

### ISSUE THREAD

**Issue by senmm** [aws-samples/amazon-s3-datalake-handson#2]
There are some broken links in lab1 [section3](https://github.com/aws-samples/amazon-s3-datalake-handson/blob/master/JP/lab1/README.md#section3%E3%81%BE%E3%81%A8%E3%82%81) [JP].
These following links are nothing in JP/lab1 directory.

![image](https://user-images.githubusercontent.com/63241411/141670245-faf6b2d5-f4d5-42e7-98d5-6ee217581734.png)

**Comment by KazutakaKubo** [comment]
Thank you for pointing it out. Response completed.
